"""Create initial database schema

Revision ID: 0c5186db109d
Revises: 
Create Date: 2025-08-10 19:26:41.281847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c5186db109d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'choices',
        existing_comment='문제에 대한 선택지',
        schema=None
    )
    op.alter_column('memes', 'year',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('memes', 'month',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_table_comment(
        'memes',
        existing_comment='밈 컨텐츠 정보',
        schema=None
    )
    op.drop_table_comment(
        'questions',
        existing_comment='퀴즈에 포함된 문제',
        schema=None
    )
    op.drop_table_comment(
        'quiz_attempts',
        existing_comment='사용자의 퀴즈 응시 기록',
        schema=None
    )
    op.drop_table_comment(
        'quizzes',
        existing_comment='밈 지식 퀴즈 정보',
        schema=None
    )
    op.drop_table_comment(
        'tags',
        existing_comment='밈 관련 태그',
        schema=None
    )
    op.drop_table_comment(
        'user_answers',
        existing_comment='사용자의 개별 문제 답변 기록',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'user_answers',
        '사용자의 개별 문제 답변 기록',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'tags',
        '밈 관련 태그',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'quizzes',
        '밈 지식 퀴즈 정보',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'quiz_attempts',
        '사용자의 퀴즈 응시 기록',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'questions',
        '퀴즈에 포함된 문제',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'memes',
        '밈 컨텐츠 정보',
        existing_comment=None,
        schema=None
    )
    op.alter_column('memes', 'month',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('memes', 'year',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.create_table_comment(
        'choices',
        '문제에 대한 선택지',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###
