"""Add region column to memes table

Revision ID: 1cb0176e5248
Revises: d7db213daca1
Create Date: 2025-10-06 14:45:15.219996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb0176e5248'
down_revision: Union[str, Sequence[str], None] = 'd7db213daca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memes', sa.Column('region', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memes', 'region')
    # ### end Alembic commands ###
